export const THREE = await import('https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js');
export const DURATION=10;
export const C={ink:0x09121f,panel:0x111b2b,white:0xf4f7fb,cyan:0x45d9ff,blue:0x7ea2ff,magenta:0xff5dcb,amber:0xffc65b,violet:0xb990ff,red:0xff6f7d};
export const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
export const range=(t,a,b)=>clamp((t-a)/(b-a));
export const lerp=(a,b,t)=>a+(b-a)*t;
export const smooth=t=>{t=clamp(t);return t*t*(3-2*t)};
export const ease=t=>1-Math.pow(1-clamp(t),3);
export const easeIO=t=>{t=clamp(t);return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2};

const canvas=document.getElementById('stage');
export const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true});
renderer.setClearColor(0x00ff00,1); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.1; renderer.shadowMap.enabled=true;
export const scene=new THREE.Scene(); scene.background=new THREE.Color(0x00ff00);
export const camera=new THREE.PerspectiveCamera(38,16/9,.1,100);
scene.add(new THREE.HemisphereLight(0xeaf4ff,0x06101c,2.2));
const key=new THREE.DirectionalLight(0xffffff,3.2);key.position.set(8,10,12);key.castShadow=true;scene.add(key);
const rim=new THREE.PointLight(C.cyan,34,40,2);rim.position.set(-7,2,7);scene.add(rim);
const fill=new THREE.PointLight(C.magenta,18,30,2);fill.position.set(6,-4,8);scene.add(fill);
export function resize(){const w=innerWidth,h=innerHeight;renderer.setPixelRatio(1);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()} addEventListener('resize',resize);resize();

function rrShape(w,h,r){const s=new THREE.Shape(),x=-w/2,y=-h/2,q=Math.min(r,w/2,h/2);s.moveTo(x+q,y);s.lineTo(x+w-q,y);s.quadraticCurveTo(x+w,y,x+w,y+q);s.lineTo(x+w,y+h-q);s.quadraticCurveTo(x+w,y+h,x+w-q,y+h);s.lineTo(x+q,y+h);s.quadraticCurveTo(x,y+h,x,y+h-q);s.lineTo(x,y+q);s.quadraticCurveTo(x,y,x+q,y);return s}
function rr2(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function rgba(hex,a){const h=hex.replace('#',''),n=parseInt(h,16);return `rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${a})`}
export function texture({title='',sub='',accent='#45d9ff',big='',badge='',kind='list',lines=[]}={}){const c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.textBaseline='middle';x.fillStyle='rgba(245,249,255,.96)';x.font='700 62px Arial';if(title)x.fillText(title,54,72);x.fillStyle='rgba(207,219,238,.72)';x.font='500 29px Arial';if(sub)x.fillText(sub,56,126);x.fillStyle=accent;if(badge){x.font='700 24px Arial';const m=x.measureText(badge).width+34;rr2(x,1024-m-44,42,m,42,18);x.fill();x.fillStyle='#08131f';x.fillText(badge,1024-m-27,63);x.fillStyle=accent}if(big){x.font='800 104px Arial';x.fillText(big,56,276)}if(kind==='list')lines.slice(0,4).forEach((v,i)=>{const yy=188+i*72;x.fillStyle=i? 'rgba(255,255,255,.045)':rgba(accent,.17);rr2(x,48,yy-28,928,56,20);x.fill();x.fillStyle=i?'rgba(231,238,249,.82)':accent;x.font=`${i?'600':'700'} 27px Arial`;x.fillText(v,78,yy);x.fillStyle='rgba(255,255,255,.18)';rr2(x,820,yy-8,112,15,8);x.fill()});if(kind==='chart'){x.strokeStyle=accent;x.lineWidth=8;x.lineCap='round';x.lineJoin='round';x.beginPath();[[60,380],[190,330],[310,352],[440,245],[565,278],[690,170],[820,202],[950,128]].forEach(([px,py],i)=>i?x.lineTo(px,py):x.moveTo(px,py));x.stroke();x.fillStyle=rgba(accent,.12);x.lineTo(950,430);x.lineTo(60,430);x.closePath();x.fill()}if(kind==='wave'){x.fillStyle=accent;for(let i=0;i<54;i++){const h=26+Math.abs(Math.sin(i*.73))*90+Math.abs(Math.cos(i*.23))*34;rr2(x,58+i*16.2,326-h/2,7,h,4);x.fill()}}if(kind==='route'){x.strokeStyle='rgba(255,255,255,.11)';x.lineWidth=2;for(let i=0;i<7;i++){x.beginPath();x.moveTo(70,185+i*42);x.lineTo(950,185+i*42);x.stroke()}x.strokeStyle=accent;x.lineWidth=11;x.lineCap='round';x.beginPath();x.moveTo(90,405);x.bezierCurveTo(260,300,360,420,515,280);x.bezierCurveTo(680,130,785,250,930,155);x.stroke()}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());t.needsUpdate=true;return t}
function faceGeometry(w,h,r){const g=new THREE.ShapeGeometry(rrShape(w,h,r));g.computeBoundingBox();const p=g.attributes.position,u=g.attributes.uv,b=g.boundingBox,dx=b.max.x-b.min.x,dy=b.max.y-b.min.y;for(let i=0;i<p.count;i++)u.setXY(i,(p.getX(i)-b.min.x)/dx,(p.getY(i)-b.min.y)/dy);u.needsUpdate=true;return g}
function textureDecal(w,h,map,z){const fm=new THREE.MeshBasicMaterial({map,transparent:true,alphaTest:.008,toneMapped:false,side:THREE.DoubleSide,depthTest:false,depthWrite:false});const f=new THREE.Mesh(new THREE.PlaneGeometry(w,h),fm);f.position.z=z;f.renderOrder=20;return f}
export function panel(w,h,{r=.24,d=.16,color=C.panel,opacity=.98,edge=C.cyan,eo=.22,map=null}={}){const g=new THREE.Group();const geom=new THREE.ExtrudeGeometry(rrShape(w,h,r),{depth:d,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:Math.min(.055,r*.3),bevelThickness:.045,curveSegments:16});geom.translate(0,0,-d/2);const body=new THREE.Mesh(geom,new THREE.MeshStandardMaterial({color,transparent:opacity<1,opacity,roughness:.34,metalness:.35}));body.castShadow=true;body.receiveShadow=true;g.add(body);const em=new THREE.MeshBasicMaterial({color:edge,transparent:true,opacity:eo,side:THREE.DoubleSide,depthWrite:false});const e=new THREE.Mesh(faceGeometry(w*1.008,h*1.008,r*1.02),em);e.position.z=d/2+.006;e.renderOrder=1;g.add(e);if(map)g.add(textureDecal(w*.90,h*.82,map,d/2+.035));return g}
export function chip(w=.72,h=.28,color=C.cyan){return panel(w,h,{r:.13,d:.09,color:0x18253a,edge:color,eo:.65})}
export function line(points,color=C.cyan,rad=.035){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)),false,'centripetal');return new THREE.Mesh(new THREE.TubeGeometry(curve,64,rad,10,false),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.65,roughness:.3,metalness:.1}))}
export function arc(r0,r1,a0,a1,depth=.12,color=C.amber){const s=new THREE.Shape(),n=36;for(let i=0;i<=n;i++){const a=lerp(a0,a1,i/n),x=Math.cos(a)*r1,y=Math.sin(a)*r1;i?s.lineTo(x,y):s.moveTo(x,y)}for(let i=n;i>=0;i--){const a=lerp(a0,a1,i/n);s.lineTo(Math.cos(a)*r0,Math.sin(a)*r0)}s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth,bevelEnabled:true,bevelSize:.025,bevelThickness:.025,bevelSegments:2});g.translate(0,0,-depth/2);return new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.22,roughness:.28,metalness:.25}))}
export function world(){const g=new THREE.Group();scene.add(g);return g}
export function depth(root,accent=C.cyan){const a=panel(3.6,1,{r:.28,d:.08,color:0x101a2a,edge:accent,eo:.11});a.position.set(-5.8,3.4,-4.8);a.rotation.set(-.08,.28,-.08);root.add(a);const b=panel(3.1,.85,{r:.26,d:.08,color:0x101a2a,edge:C.magenta,eo:.10});b.position.set(5.6,-3.2,-5.8);b.rotation.set(.12,-.35,.06);root.add(b)}
export function fade(o,t,a,b,s=.7){const q=ease(range(t,a,b));o.visible=q>0;o.scale.setScalar(lerp(s,1,q))}
export function cam(t,k){let a=k[0],b=k[k.length-1];for(let i=0;i<k.length-1;i++)if(t>=k[i].t&&t<=k[i+1].t){a=k[i];b=k[i+1];break}const q=easeIO(range(t,a.t,b.t));camera.position.set(lerp(a.p[0],b.p[0],q),lerp(a.p[1],b.p[1],q),lerp(a.p[2],b.p[2],q));camera.lookAt(lerp(a.l[0],b.l[0],q),lerp(a.l[1],b.l[1],q),lerp(a.l[2],b.l[2],q));camera.rotation.z=lerp(a.r||0,b.r||0,q)}
export function render(){renderer.render(scene,camera)}
